apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-debug
  labels:
    chart: {{ .Chart.Name }}
    version: {{ .Chart.Version | quote }}
    {{- with .Values.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  release_name: {{ .Release.Name }}
  release_namespace: {{ .Release.Namespace }}
  release_version: {{ .Release.Revision | quote }}
  image_full: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
  service_type: {{ .Values.service.type | upper }}
  replica_count: {{ .Values.replicaCount | int }}
