replicaCount: 1

image:
  repository: ghcr.io/stefanprodan/podinfo
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9898

ingress:
  enabled: false
  className: ""
  host: podinfo.local
  path: /

resourses:
  limit:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

podinfo:
  level: info
  massage: "Hello from my Helm chart!"
  ui:
    color: "#34577c"
